### ISSUE TITLE
add no_std option

### ISSUE THREAD

**Issue by oezgurmakkurt** [oezgurmakkurt/blasoxide#9]

**Comment by VanioBegic** [comment]
I have no other way, but why was the repository restarted? It seemed very promising really

**Comment by oezgurmakkurt** [comment]
There were performance problems with code, level 1 functions and gemm microkernels need to be rewritten in assembly. I am going to re-implement everything there was before. So it shouldn't be a problem

**Comment by oezgurmakkurt** [comment]
@VanioBegic Ok, I reverted the reset, because I didn't find the performance improvement was worth doing kernels in assembly. I should've done this in a different branch probably.

**Comment by oezgurmakkurt** [comment]
closing this since I don't get why this would be useful.
